# Generated by Django 5.2.3 on 2025-06-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanhacoleta',
            options={'verbose_name': 'CampanhaColeta'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade'},
        ),
        migrations.AlterModelOptions(
            name='historicodescartes',
            options={'verbose_name': 'HistóricoDescarte'},
        ),
        migrations.AlterModelOptions(
            name='ocupacao',
            options={'verbose_name': 'Ocupacao'},
        ),
        migrations.AlterModelOptions(
            name='participacaocampanha',
            options={'verbose_name': 'ParticipacaoCampanha'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa'},
        ),
        migrations.AlterModelOptions(
            name='pontocoleta',
            options={'verbose_name': 'PontoColeta'},
        ),
        migrations.AlterModelOptions(
            name='residuodescartado',
            options={'verbose_name': 'ResíduoDescartado'},
        ),
        migrations.AlterModelOptions(
            name='tiporesiduo',
            options={'verbose_name': 'TipoResíduo'},
        ),
        migrations.AlterField(
            model_name='residuodescartado',
            name='ponto_coleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pontocoleta', verbose_name='PontoColeta'),
        ),
    ]
